### ISSUE TITLE
单晓林CI/CD

### ISSUE THREAD

**Issue by zhendong233** [zhendong233/zzd-qna-bot#2]
### CI/CD创建步骤
* 把代码仓库down到本地创建一个react app—— `npx create-react-app LT`
* 导入npm包——`npm install`
* 着手编写dockfile,dockerfile我理解为自定义docker镜像的配置以及docker镜像要执行的命令。
```
FROM nginx
COPY build /usr/share/nginx/html
RUN apt-get update
RUN apt-get install openssh-server -y  \
     && echo "root:Docker!" | chpasswd 
COPY sshd_config /etc/ssh/
RUN mkdir /run/sshd
CMD /usr/sbin/sshd & service nginx start & tail -f /dev/null

EXPOSE 80 2222
```
* [配置ssh连接](https://docs.microsoft.com/en-au/azure/app-service/containers/configure-custom-container) 
* 创建pipeline, `.yml`文件编写如下

```
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script:
    npm install
  displayName: '1'
- script:
    npm run build
  displayName: '2'
- script:
    docker build -t shanxiaolin/dockerone:laster ./ 
  displayName: '3'
- script:
     docker login -u $(dockeruser) -p $(dockerpass)
  displayName: '4'
- script:
    docker push shanxiaolin/dockerone:laster
  displayName: '5'
  ```
* 上面脚本用到了docker hub，docker hub是一个镜像存储库，与git hub存储代码类似
* 创建一个容器配置容器
